name = input("What is your name? ")
student_id = input("What is your student id? ")
department = input("What is your department? ")
account = input("What is your github account? ")
goal = input("What is your goal? ")
print("\n Student profile")
print(f"Name: {name}")
print(f"student id: {student_id}")
print(f"Department: {department}")
print(f"Account: {account}")
print(f"Goal: {goal}")
